### ISSUE TITLE
Wrong explanation for optional program on apply page.

### ISSUE THREAD

**Issue by indyaah** [talentspace/website#1]
The text for optional program reads

_Write a program in your favourite programming language to print the multiples of 2 and 5 between..._

It should be 2 **OR** 5.

Though I understand it's minor and the example output prevents any confusion arising, could not help reporting. :)

**Comment by ershad** [comment]
@indyaah fixed it, thank you so much for reporting :)

**Comment by indyaah** [comment]
:+1:
